# Generated by Django 4.2.2 on 2023-06-27 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopole',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='peopole',
            name='likes',
            field=models.CharField(choices=[('Li', 'Like'), ('Di', 'Dislike'), ('Ot', 'Other')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopole',
            name='yeahBirth',
            field=models.IntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
            preserve_default=False,
        ),
    ]
