# Generated by Django 4.2.2 on 2023-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_peopole_active_peopole_likes_peopole_yeahbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('descriotion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Peopole',
            new_name='People',
        ),
    ]
